### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by brononius** [skorokithakis/gr8w8upd8m8#7]
Hello,
I'm trying this with the latest RaspberryPi Zero.
But sadly, I encounter a lot of errors. Guess it has to do with the python version?
I'm not a programmer, so not sure what I can do next. :$

>   python3 gr8w8upd8m8.py 00:1F:C5:A8:44:32
>   File "/diy/gr8w8upd8m8/gr8w8upd8m8.py", line 44
>  print "Starting measurement."
>   SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Starting measurement.")?

I've added () in all lines where print is found, but then I've got a main error? 

>python3 test.py 00:1F:C5:A8:44:32
>Traceback (most recent call last):
>  File "/diy/tideliek/test.py", line 305, in <module>
>    main()
>  File "/diy/tideliek/test.py", line 275, in main
>    board = Wiiboard(processor)
>  File "/diy/tideliek/test.py", line 82, in __init__
>    for i in xrange(3):
>NameError: name 'xrange' is not defined

when I tried it with python2.7.18, I'm getting a bluetooth issue I can't solve.
> python gr8w8upd8m8.py 00:1F:C5:A8:44:32
> Traceback (most recent call last):
>  File "gr8w8upd8m8.py", line 5, in <module>
>    import bluetooth
> ImportError: No module named bluetooth

**Comment by skorokithakis** [comment]
Yes, it's either the Python version (you need 2.7) or you need the Bluetooth library installed. Unfortunately, even if you got this working, it still wouldn't pair. I haven't been able to get it to work again for ages. If you manage to, please let me know!

**Comment by brononius** [comment]
I've got Python 2.7.18. 
But I keep on getting the message 'No moduel named bluetooth'. 

>Traceback (most recent call last):
>  File "gr8w8upd8m8.py", line 5, in <module>
>    import bluetooth
>ImportError: No module named bluetooth


I've got the feeling I can connect the wiiboard, with a raspberry pi Zero.
LED is flashing while paring, and stays solid once it's trusted.

> sudo bluetoothctl
> Agent registered
> [CHG] Controller B8:27:EB:3E:6F:0C Pairable: yes
> [bluetooth]# scan on
Discovery started
[CHG] Controller B8:27:EB:3E:6F:0C Discovering: yes
[bluetooth]# power on
Changing power on succeeded
[bluetooth]# agent on
Agent is already registered
[bluetooth]# pair 00:1F:C5:A8:44:32 
Attempting to pair with 00:1F:C5:A8:44:32
Failed to pair: org.bluez.Error.AlreadyExists
[bluetooth]# connect 00:1F:C5:A8:44:32 
Attempting to connect to 00:1F:C5:A8:44:32
[CHG] Device 00:1F:C5:A8:44:32 Connected: yes
Connection successful
[CHG] Device 00:1F:C5:A8:44:32 ServicesResolved: yes
[CHG] Device E5:DA:FD:AC:2D:C8 RSSI: -74
[Nintendo RVL-WBC-01]# trust 00:1F:C5:A8:44:32 
Changing 00:1F:C5:A8:44:32 trust succeeded
[CHG] Device E5:DA:FD:AC:2D:C8 RSSI: -86
[Nintendo RVL-WBC-01]# 

I read a lot of things that it's hassle to connect. Read a lot stories that you need to push the button each time and so. If this is the case, my workaround would be the pinout of the RP to the bluetooth buttton. But first try to read the values.
